### ISSUE TITLE
al:draw-text CONSes like crazy

### ISSUE THREAD

**Issue by BlueFlo0d** [resttime/cl-liballegro#29] opened 2021-04-17 20:00 UTC
I'm building an editor/IDE on `cl-liballegro` and render lots of text, and I find it using lots of CPU/memory even when idle. Therefore I run the profiler on some suspicious functions.

```
  seconds  |     gc     |    consed   |  calls  |  sec/call  |  name  
-----------------------------------------------------------
     4.384 |      0.026 | 164,167,856 | 134,420 |   0.000033 | CL-LIBALLEGRO:DRAW-TEXT
     0.126 |      0.000 |   2,916,352 |  57,200 |   0.000002 | DRAW-TEXT%%
     0.117 |      0.000 |   4,325,040 |   2,860 |   0.000041 | CL-LIBALLEGRO:DRAW-LINE
     0.000 |      0.000 |   5,766,640 |  97,240 |   0.000000 | DISPLAY
     0.000 |      0.000 |      65,536 |  38,610 |   0.000000 | DISPLAY-CONS-BODY
-----------------------------------------------------------
     4.627 |      0.026 | 177,241,424 | 330,330 |            | Total
```
It turns out that `al:draw-text` uses most of the resource. This shouldn't be the case since I'm using the quite common idiom of calling `al:draw-text` to render the frame (as in emacs frame) every frame (as in FPS).

I suspect it's because of CFFI doing lots of unnecessary copies (however, those should go into foreign memory and not be counted as CONS?). Any ideas?

**Comment by resttime** [comment] 2021-04-18 04:38
I'm not completely sure but there might be extra cons'ing going on converting from lisp memory to foreign memory with `al:draw-text` through the `color` and `text` parameters.

https://github.com/resttime/cl-liballegro/blob/6060e6869140b02d69bff78947c730a16dfc7267/src/ffi-functions/addons/font.lisp#L17-L22

In the context of a text editor, I suspect `text` is the heavy hitter with the conversion of text living in lisp memory to foreign memory. If the issue is what I think it is, ensuring the text lives in foreign memory without reallocating on every render when idling might fix it: https://common-lisp.net/project/cffi/manual/html_node/Strings.html

**Comment by resttime** [comment] 2021-04-19 05:55
Hmmm, side thing but I might work on adding the UTF-8 functionality Allegro 5 provides to the bindings. It might come in handy for working with text.

**Comment by resttime** [comment] 2021-04-26 22:20
All the UTF-8 goodies from Allegro5 are added now

**Comment by BlueFlo0d** [comment] 2021-04-27 18:08
Ah, thanks! This may be useful for internationalizing games. In my particular case, I now took a more radical approach, storing S-expr instead of character arrays (strings), and use character as the finest element.
So I basically store `((s e t q) (x) (1))`. And now I don't do any string copying so I expect it won't be a problem.

I suspect that color struct copying will now become a problem, see the benchmark of `draw-line` calls. Do you know a way to eliminate copying of that struct? (I haven't really tested because I need to rewrite 90% of my experimental code).

Also just FYI, this thread is helpful for explaining what I'm doing
https://lists.gnu.org/archive/html/emacs-tangents/2021-04/msg00005.html

**Comment by resttime** [comment] 2021-04-28 01:42
> Ah, thanks! This may be useful for internationalizing games. In my particular case, I now took a more radical approach, storing S-expr instead of character arrays (strings), and use character as the finest element.
> So I basically store `((s e t q) (x) (1))`. And now I don't do any string copying so I expect it won't be a problem (I draw things glyph by glyph).
> 
Interesting!

> I suspect that color struct copying will now become a problem, see the benchmark of `draw-line` calls. Do you know a way to eliminate copying of that struct? (I haven't really tested because I need to rewrite 90% of my experimental code).
> 
It is possible to destruct the color struct as function parameters in the CFFI `defcfun` definitions as long as the type sizes align with the function calls. That's how it was when these bindings were first written to avoid [libffi](https://sourceware.org/libffi/) as a dependency.  This broke cross-platform compatibility although since platforms can define types to a different sizes. See if redefining `draw-line` works like:

```lisp
;; libffi pass struct by value
(defcfun ("al_clear_to_color" clear-to-color) :void (color (:struct color)))

;; destruct in function definition
;; depending on platform it might not be :float to align with function parameter calls
;; IIRC this is due to how arguments are pushed onto the stack
(defcfun ("al_clear_to_color" clear-to-color) :void (r :float) (g :float) (b :float) (a :float))
```

Do check for the performance gained/loss if so and whether this struct is being created at every render. The fixed cost of passing the struct by value with libffi calls might be small since it's four floats:
https://github.com/resttime/cl-liballegro/blob/6060e6869140b02d69bff78947c730a16dfc7267/src/types/graphics.lisp#L4-L8

> Also just FYI, this thread is helpful for explaining what I'm doing
> https://lists.gnu.org/archive/html/emacs-tangents/2021-04/msg00005.html
>
Neat, will take a look

**Comment by resttime** [comment] 2021-04-28 02:02
Oh right, there's maybe one more possible culprit for increased conses. The `c-float`, `c-int`,`c-double`, and etc. are convenience types for the user defined by the bindings [here](https://github.com/resttime/cl-liballegro/blob/master/src/types/types.lisp) that coerce args to the type. CFFI resolves these types through multiple dispatch with `defmethod` which might add more conses instead of using the `float` type directly. 

Replacing `c-float` with `:float` might further reduce the conses. Dunno how much of a performance difference it makes although.
https://github.com/resttime/cl-liballegro/blob/f1337509d443641faade44e07057d897b42a9b83/src/ffi-functions/addons/primatives.lisp#L11-L14

**Comment by resttime** [comment] 2022-10-04 18:47
Making the assumption that as a support issue this has reached to conclusion. Closing to clean, feel free to open another if something pops up.

**Closed by resttime** 2022-10-04 18:47 UTC
